import { NextRequest, NextResponse } from 'next/server';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API);

// Helper function to escape HTML
const escapeHtml = (unsafe: string): string => {
   return unsafe
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
};

export const POST = async (req: NextRequest) => {
   try {

      const { userEmail, userName, message} = await req.json();
      
      // Validate input
      if (!userEmail || !userName || !message) {
         return NextResponse.json({
            success: false,
            error: 'Missing required fields'
         }, { status: 400 });
      }
      
      const res = await resend.emails.send({
         from: process.env.FROM_DOMAIN || '',
         to: process.env.TO_EMAIL || '',
         replyTo: userEmail,
         subject: `New Message from ${escapeHtml(userName)}`,
         html: htmlTemplate({userEmail, userName, message}),
         text: textTemplate({userEmail, userName, message})
      });

      return NextResponse.json({
         success: true,
         data: res
      })

   } catch (error) {
      console.log(error);
      return NextResponse.json({
         error: error,
         success: false
      })
   }
}


const htmlTemplate = (
   {userName, userEmail, message}: {userName: string, userEmail: string, message: string}) => {
   return (
      `
      <div style="font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px; background-color: #ffffff; border: 1px solid #e5e7eb; border-radius: 8px;">
         <h2 style="margin-bottom: 24px; font-size: 20px; color: #111827; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px;">
            New Contact Form Submission
         </h2>
         <table cellpadding="0" cellspacing="0" style="width: 100%; font-size: 16px; color: #374151;">
            <tr><td style="padding: 8px 0; width: 100px;"><strong>Name:</strong></td><td>${escapeHtml(userName)}</td></tr>
            <tr><td style="padding: 8px 0;"><strong>Email:</strong></td><td>${escapeHtml(userEmail)}</td></tr>
         </table>
         <div style="margin-top: 24px;">
            <p style="font-size: 16px; color: #374151; margin-bottom: 8px;"><strong>Message:</strong></p>
            <div style="padding: 16px; background-color: #f9fafb; border: 1px solid #e5e7eb; border-radius: 4px; color: #1f2937; line-height: 1.5;">
            ${escapeHtml(message).replace(/\n/g, '<br />')}
            </div>
         </div>
         <p style="font-size: 14px; color: #9ca3af; margin-top: 40px; text-align: center;">
            This email was generated by your portfolio contact form on monomonu.me
         </p>
      </div>
      `
   )
}


const textTemplate = (
   {userName, userEmail, message}: {userName: string, userEmail: string, message: string}) => {
   return (
      `
      New Contact Form Submission

      Name: ${escapeHtml(userName)}
      Email: ${escapeHtml(userEmail)}

      Message:
      ${escapeHtml(message)}

      —
      This message was sent from your portfolio contact form at monomonu.me
      `
   )
}